# fly.toml app configuration file generated for counterfeitcontent on 2024-01-28T21:12:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "counterfeitcontent"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
